
- name: ensure registration of default private domain names
  local_action: route53
  sudo: False
  args:
    private_zone: true
    command: create
    overwrite: True
    zone: "{{item.zone}}"
    record: "{{item.record}}"
    type: A
    ttl: 300
    value: "{{item.value}}" 
    aws_access_key: "{{aws_access_key_id}}"
    aws_secret_key: "{{aws_secret_access_key}}"
  with_items:
    - { record: "{{subdomain}}.{{private_domain}}", zone: "{{private_domain}}", value: "{{ansible_eth0.ipv4.address}}" }

- name: ensure registration of default public domain names
  local_action: route53
  sudo: False
  args:
    private_zone: false
    command: create
    overwrite: True
    zone: "{{item.zone}}"
    record: "{{item.record}}"
    type: A
    ttl: 300
    value: "{{item.value}}" 
    aws_access_key: "{{aws_access_key_id}}"
    aws_secret_key: "{{aws_secret_access_key}}"
  with_items:
    - { record: "{{subdomain}}.{{public_domain}}", zone: "{{public_domain}}", value: "{{ lookup('dig', inventory_hostname) }}" }

