---
- name: set facts
  set_fact:
    app_src_project_root: "{{app_src_root}}{{app.src_path_prefix|default('', true)}}"

- name: install deploy ssh key
  sudo: true
  sudo_user: "{{app.user}}"
  copy:
    content="{{app.deploy_rsa_key}}"
    dest=/home/{{app.user}}/.ssh/id_rsa-{{app_name}}
    owner={{app.user}}
    group={{app.user}}
    mode=0600

- name: Deploy Source
  sudo: true
  sudo_user: "{{app.user}}"
  git: 
    accept_hostkey=True
    repo="{{app.repo_url}}"
    dest="{{app_src_project_root}}" 
    remote="{{app.repo_remote}}" 
    version="{{app.repo_branch}}"
    key_file="/home/{{app.user}}/.ssh/id_rsa-{{app_name}}"

- name: clean stray files from source dir
  sudo: true
  sudo_user: "{{app.user}}"
  command: "git clean -df"
  args:
    chdir: "{{app_src_project_root}}"

- name: Install Python app dependencies from pip
  sudo: true
  sudo_user: "{{app.user}}"
  pip:
    extra_args="-i {{pypi_mirror_url}}"
    requirements={{app_src_root}}/requirements.txt 
    virtualenv={{app_venv_root}} 
    state=latest
#"

- include: django/deploy.yml
    app={{apps[app_name]}}
  when: "'django' in app.build_steps"

- name: Install app settings file
  sudo: true
  sudo_user: "{{app.user}}"
  template:
    src="{{app.python_app_conf_tmpl}}"
    dest="{{app.python_app_conf_path}}"
    owner={{app.user}}
    group={{app.user}}

- name: install custom wsgi
  sudo: true
  sudo_user: "{{app.user}}"
  template:
    src="{{app.wsgi_tmpl}}"
    dest="{{app.wsgi_path}}"
    owner={{app.user}}
    group={{app.user}}
  when: app.wsgi_tmpl is defined

- name: pyc cleanup
  sudo: true
  command: pyclean {{app_src_project_root}}

- name: ensure file ownership of source
  sudo: true
  file:
    path={{app_src_root}}
    owner={{app.user}}
    group={{app.user}}
    recurse=true

- include: deploy-runonce.yml
    app={{apps[app_name]}}
  when: app_runonce_build

# POST DEPLOY    
- name: restart circus app
  command: "circusctl restart {{app_name}}"
  when: "'circus' in app.build_steps"

# TODO: HUP for other runners (supervisor, uwsgi, etc..)
