---

- name: set facts
  set_fact:
    app_root: "{{apps_root}}/{{app_name}}"
    app_src_root: "{{apps_root}}/{{app_name}}/src"
    app_log_root: "{{apps_log_root}}/{{app_name}}"
    app_venv_root: "{{apps_root}}/{{app_name}}/venv"
    app_venv_pip_path: "{{apps_root}}/{{app_name}}/venv/bin/pip"
    app_venv_python_path: "{{apps_root}}/{{app_name}}/venv/bin/python"

- name: install common system packages
  become: True
  apt:
    pkg={{item}} 
    state=present
  with_items:
    - git-core
    - python-setuptools
    - python-pip
    - ntp
  when: do_web or do_app
  tags:
    - do_web
    - do_app

- include: web.yml
    app={{apps[app_name]}}
  become: true
  become_user: "{{deploy_user}}"
  when: do_web
  tags:
    - do_web

- include: app.yml
    app={{apps[app_name]}}
  become: true
  become_user: "{{deploy_user}}"
  when: do_app
  tags:
    - do_app

- include: webapp.yml
    app={{apps[app_name]}}
  become: true
  become_user: "{{deploy_user}}"
  when: do_web and do_app
  tags:
    - do_web
    - do_app

- include: deploy.yml
    app={{apps[app_name]}}
  become: true
  become_user: "{{deploy_user}}"
  when: do_deploy
  tags:
    - do_deploy
