---

# circus config for app servers
- name: App config for circus
  become: True
  become_user: root
  template:
    src=circus-app.ini.j2
    dest="{{circus_config_dir}}/include/{{app_name}}.ini"
  notify:
    - restart circusd

- name: ensure circusd service started
  become: True
  service: name=circusd state=started enabled=yes
