---

- name: ensure server root dir exists
  file:
    path={{app.server_root_dir}}
    owner={{app.user}}
    group={{app.user}}
    state=directory
  when: app.server_root_dir is defined

# nginx config
- name: Create app config for nginx
  sudo: true
  sudo_user: root
  template:
    src={{app.nginx_app_conf_tmpl | default(nginx_app_conf_tmpl)}}
    dest={{nginx_config_dir}}/sites-available/{{app_name}}.conf
  notify:
    - restart nginx

- name: Enable app for nginx
  sudo: true
  sudo_user: root
  file:
    src={{nginx_config_dir}}/sites-available/{{app_name}}.conf
    dest={{nginx_config_dir}}/sites-enabled/{{app_name}}.conf
    state=link
  notify:
    - restart nginx
