---

- include: nodejs/app.yml
    app={{apps[app_name]}}
  when: "'nodejs' in app.build_steps"

- include: sass/app.yml
    app={{apps[app_name]}}
  when: "'sass' in app.build_steps"

- include: webapp-circus.yml
    app={{apps[app_name]}}
  when: "'circus' in app.build_steps"

- include: webapp-supervisor.yml
    app={{apps[app_name]}}
  when: "'supervisor' in app.build_steps"

- include: webapp-uwsgi.yml
    app={{apps[app_name]}}
  when: "'uwsgi' in app.build_steps"

- include: webapp-nginx.yml
    app={{apps[app_name]}}
  when: "'nginx' in app.build_steps"
