---

- name: update apt
  become: True
  action: apt update_cache=yes

- name: restart nginx
  become: True
  service: name="nginx" state=restarted

- name: restart wsgi
  become: True
  service: name="nginx" state=restarted

- name: restart circusd
  become: True
  service: name="circusd" state=restarted

- name: restart supervisor
  become: True
  service: name="supervisor" state=restarted
