---

- name: update apt
  sudo: True
  action: apt update_cache=yes

- name: restart nginx
  sudo: True
  service: name="nginx" state=restarted

- name: restart wsgi
  sudo: True
  service: name="nginx" state=restarted

- name: restart circusd
  sudo: True
  service: name="circusd" state=restarted

- name: restart supervisor
  sudo: True
  service: name="supervisor" state=restarted
