---

- name: deploy private key
  copy:
    content={{app.deploy_rsa_key}}
    dest=/home/{{app.user}}/.ssh/id_rsa-{{app_name}}
    mode=0600

- name: Deploy Source
  git: 
    accept_hostkey=True
    repo={{app.repo_url}} 
    dest={{app_src_root}} 
    remote={{app.repo_remote}} 
    version={{app.repo_branch}}
    key_file=/home/{{app.user}}/.ssh/id_rsa-{{app_name}}

- name: Install Python app dependencies from pip
  pip:
    extra_args="-i {{pypi_mirror_url}}"
    requirements={{app_src_root}}/requirements.txt 
    virtualenv={{app_venv_root}} 
    state=present
#"

- include: django/deploy.yml
    app={{apps[app_name]}}
  when: "'django' in app.build_steps"

- name: Install app settings file
  template:
    src="{{app.python_app_conf_tmpl}}"
    dest="{{app.python_app_conf_path}}"

- name: install custom wsgi
  template:
    src="{{app.wsgi_tmpl}}"
    path="{{app.wsgi_path}}"
  when: app.wsgi_tmpl is defined

- name: pyc cleanup
  command: pyclean {{app_src_root}}
