---
- name: set facts
  set_fact:
    app_root: "{{apps_root}}/{{app_name}}"
    app_log_root: "{{apps_log_root}}/{{app_name}}"
    app_src_root: "{{apps_root}}/{{app_name}}/src"
    app_venv_root: "{{apps_root}}/{{app_name}}/venv"
    app_venv_pip_path: "{{apps_root}}/{{app_name}}/venv/bin/pip"
    app_venv_python_path: "{{apps_root}}/{{app_name}}/venv/bin/python"

- name: ensure apt cache is up to date
  sudo: True
  action: apt update_cache=yes

- name: install common system packages
  sudo: True
  apt:
    pkg={{item}} 
    state=present
  with_items:
    - git-core
    - python-setuptools

- include: deploy.yml
    app={{apps[app_name]}}

- include: runonce.yml
    app={{apps[app_name]}}
  when: app_runonce_build
